name: Publish

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
      
    steps:
    - name: Install Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
        
    - name: Install Flutter
      uses: subosito/flutter-action@v2     
      
    - name: Publish to pub.dev
      run: flutter pub publish --force
